config/routes.rb
Rails.application.routes.draw do
  get "model/index"
  get "model/new"
  get "article1/index"
  get "article1/new"
  root "employees#index"
  get "employ", to: "employees#show"
  resources :employees do
    resources :update
  end
  get "employees/:id", to: "employees#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord

    
    
    end

app/models/employee.rb
class Employee < ApplicationRecord 
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  wrap_parameters format: [:json, :xml]
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  private

  def record_not_found
    render plain: "404 Not Found", status: 404
  end
end

app/controllers/article1_controller.rb
class Article1Controller < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
  wrap_parameters format: [:json, :xml, :url_encoded_form, :multipart_form]

  def index
    @product = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
  end

  def delete
  end

  def action
    @employee = Employee.find(params[:id])
  end
end

private

def product_params
  params.require(:product).permit(:name, :price, :credit, :debit)
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.all
  end

  def new
    @employee = Employee.new
    respond_to do |format|
      format.html
      format.pdf do
        pdf = prawn::Document.new
        pdf.text "hello"
        send_data pdf.render, filename: "member.pdf", type: "application/pdf", disposition: "inline"
      end
    end
  end

  def create
    session[:employe_id] = employee.id
    redirect_to employees_path
    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to employees_path, notice: "employee has been created"
    else
      render :new
    end
  end

  def update
    @employee = Employee.find(params[:id])
    #@employee.re4e

    if @employee.update(employee_params)
      redirect_to employees_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    #reset_session
    #redirect_to employee_update_path
    #@employees.destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    #redirect_to employees, notice: 'employees has succesfully deleted.'
    redirect_to employee_update_path
    #head :no_content }
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def show
    @employees = Employee.all
  end

  private

  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :email, :city, :country, :pincode)
  end
end

app/controllers/model_controller.rb
class ModelController < ApplicationController
  def index
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article1_helper.rb
module Article1Helper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/model_helper.rb
module ModelHelper
end

app/helpers/myhelper_helper.rb
module MyhelperHelper
        def greeting(name)
          "Hello, #{name}!"
        end
      end
      

app/views/article/create.html.erb
<h1>Article#create</h1>
<p>Find me in app/views/article/create.html.erb</p>

app/views/article/delete.html.erb
<h1>Article#delete</h1>
<p>Find me in app/views/article/delete.html.erb</p>

app/views/article/index.html.erb
<h1>Article#index</h1>
<p>this is partial index</p>
<>

app/views/article/new.html.erb
<%# <h1>Article#new</h1>
<p>Find me in app/views/article/new.html.erb</p> %>
<h1>New Product</h1>

<%= form_with model: @products do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :price %><br>
    <%= form.text_area :price %>
  </div>
   <div>
    <%= form.label :credit %><br>
    <%= form.text_area :credit%>
  </div>
  <div>
    <%= form.label :debit %><br>
    <%= form.text_area :debit %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/article/update.html.erb
<h1>Article#update</h1>
<p>Find me in app/views/article/update.html.erb</p>

app/views/article1/index.html.erb
<h1>Article1#index</h1>
<p>Find me in app/views/article1/index.html.erb</p>

app/views/article1/new.html.erb
<h1>Article1#new</h1>
<p>Find me in app/views/article1/new.html.erb</p>

app/views/employees/_navbaar.html.erb
<%#=javascript_include_tag "main"%>
<%=stylesheet_link_tag "main"%>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Employee-Details</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
    
      <li class="nav-item">
        <a class="nav-link" href="/employees/new">create-employee</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="/employees/show">show-employee</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/employees/update">update</a>
      </li>
     <li class="nav-item">
        <%# <a class="nav-link" href="/employees/destroy">destroy</a> %>
        <%# <a class="nav-link" href="/employees/destroy">destroy</a> %>
        <%# <a class="nav-link" href="/employees/destroy">destroy</a> %>
          <%#= link_to "delete", employee_path,:action=>"show", :controller=>"employees"%>
      </li>
     </ul>
  </div>
</nav>

app/views/employees/create.html.erb
<h1>Employees#create</h1>
<p>Find me in app/views/employees/create.html.erb</p>

app/views/employees/destroy.html.erb
<div class="card mt-5 mb-5">
<div class="card-body">
<h3 class="text-center"> <%= t('listing_employees') %> </h3>
<%= link_to "Create New Employee", employees_new_path %>
<%=flash[:notice]= "employee created...."%>
<table>
<thead>
<style>
  td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
<tr>
   <th>first_name</th>
   <th>last_name</th>
   <th>Email</th>
   <th>city</th>
   <th>state</th>
   <th>country</th>
   <th> Pincode </th>
   <th>Delete</th>
</tr>
</thead>
<tbody class="body">
<tr>
<%= @employees.each do |employee|%>
  <td><%= employee.first_name%></td>
  <td><%= employee.last_name%></td>
  <td><%= employee.email%></td>
  <td><%= employee.city%></td>
  <td><%= employee.state%></td>
  <td><%= employee.country%></td>
  <td><%= employee.pincode%></td>
  <td><%= link_to "Delete", employees_edit_path %></td>
</tr>
<%= end %>
</tbody>
</table>

app/views/employees/edit.html.erb
<%= form_with model: @employee do |form| %>
<div>
<%=form.label :first_name%><br>
<%=form.text_field :first_name%>
</div>
<div>
<%=form.label :last_name%><br>
<%=form.text_field :last_name%>
</div>
<div>
<%=form.label :email%><br>
<%=form.email_field :email%>
</div>
<div>
<%=form.label :city%><br>
<%=form.text_field :city%>
</div>
<div>
<%=form.label :state%><br>
<%=form.text_field :state%>
</div>

<div>
<%=form.label :country%><br>
<%=form.text_field :country%>
</div>
<div>
<%=form.label :Pincode%><br>
<%=form.text_field :pincode%>
</div>
<div>
<%=form.submit  name:"hello"%>
</div>
  <%= form.file_field :picture %>
<% end %>

app/views/employees/home.html.erb
<h1>this is a home</h1>

app/views/employees/new.html.erb
<%=javascript_include_tag "create"%>
<%#=link_to "pdf file",employees_path(format: 'pdf')%>
<style>
.my 
text-align:center
.center
  margin-left: auto;
  margin-right: auto;
</style>
<%= form_with model: @employee do |form|%>
<table class="center">
<div class="my">
<%=form.label :first_name %><br>
<%=form.text_field :first_name%>
</div>
<div>
<%=form.label :last_name %><br>
<%=form.text_field :last_name%>
</div>
<div>
<%=form.label :email %><br>
<%=form.email_field :email%>
</div>
<div>
<%=form.label :city %><br>
<%=form.text_field :city%>
</div>
<div>
<%=form.label :state %><br>
<%=form.text_field :state%>
</div>

<div>
<%=form.label :country %><br>
<%=form.text_field :country%>
</div>
<div>
<%=form.label :Pincode %><br>
<%=form.text_field :pincode%>
</div>
<div>
<%=form.submit name:"create employee"%>
</div>
</table>
<%end%>

app/views/employees/show.html.erb
<%# <h1>Employees#index</h1>
<p>Find me in app/views/employees/index.html.erb</p> %>

<div class="card mt-5 mb-5">
<div class="card-body">
<h3 class="text-center"> Listing Employee </h3>
<table>
<thead>
<style>
  td, th,table {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
  text-align:center;
  border:5px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
<tr>
   <th>S.no</th>
   <th>first_name</th>
   <th>last_name</th>
   <th>Email</th>
   <th>city</th>
   <th>state</th>
   <th>country</th>
   <th> Pincode </th>
   <th>Actions</th>
   <th>Delete</th>
 </tr>
</thead>
<tbody class="body">
<tr>
<% @employees.each do |employee|%>
   
  <%# @ids.each do |id| %>

  
  <td><%= employee.id %></td>
  <td><%= employee.first_name%></td>
  <td><%= employee.last_name%></td>
  <td><%= employee.email%></td>
  <td><%= employee.city%></td>
  <td><%= employee.state%></td>
  <td><%= employee.country%></td>
  <td><%= employee.pincode%></td>
  <td><%#= link_to "Edit", hello_path(employee)%></td>
  <td><%#= link_to "Delete-employee",employee_path, method: :delete %></td>
  <td><%#= link_to "Delete-employee",employ_path, method: :delete %></td>
  <%#= link_to 'employee record', employee_path(@employee) %>
  </tr>
 <% end %>
 </tbody>
 </table>

app/views/employees/special.html.erb
<% <% content_for :special do %>
  <script>alert('employee your data')</script>
<% end %> %>

app/views/employees/update.html.erb
<h1>new Student</h1>
<%= form_with model: @employee do |form|%>
<div>
<%=form.label :first_name %><br>
<%=form.text_field :first_name%>
</div>
<div>
<%=form.label :last_name %><br>
<%=form.text_field :last_name%>
</div>
<div>
<%=form.label :email %><br>
<%=form.email_field :email%>
</div>
<div>
<%=form.label :city %><br>
<%=form.text_field :city%>
</div>
<div>
<%=form.label :state %><br>
<%=form.text_field :state%>
</div>
<div>
<%=form.label :country %><br>
<%=form.text_field :country%>
</div>
<div>
<%=form.label :Pincode %><br>
<%=form.text_field :pincode%>
</div>
<div>
<%=form.submit name:"create employee"%>
</div>
<%= end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<title>
  <head>

    <title>Crudoperation</title>

    <%= yield :special %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <%= javascript_include_tag "application" %>
  </head>

  <body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
 <%= render 'employees/navbaar'%>
 <%= render 'employees/footer'%>
    <%= yield %>
    <p>Welcome! The date and time is <%= Time.now %></p>
  </body>
</html>

app/views/layouts/demo.html.erb
<h1>this is a layout</h1>

app/views/model/index.html.erb
<h1>Model#index</h1>
<p>Find me in app/views/model/index.html.erb</p>

app/views/model/new.html.erb
<h1>Model#new</h1>
<p>Find me in app/views/model/new.html.erb</p>

app/views/persons/_form.hmtl.erb
<%= form_with model: person do |form| %>
  Addresses:
  <ul>
    <%= form.fields_for :addresses do |addresses_form| %>
      <li>
        <%= addresses_form.label :kind %>
        <%= addresses_form.text_field :kind %>

        <%= addresses_form.label :street %>
        <%= addresses_form.text_field :street %>
        ...
      </li>
    <% end %>
  </ul>
<% end %>

app/views/persons/edit.html.erb
<%= render 'form', person: @person %>

app/views/persons/new.html.erb
<%= render 'form', person: @person %>